name: "GitHub App authentication"
description: ""
inputs:
  app-id:
    description: GitHub App ID
    deprecationMessage: Use 'client-id' instead.
  client-id:
    description: GitHub App Client ID
  private-key:
    description: GitHub App Private Key
runs:
  using: "composite"
  steps:
    - run: gh config set telemetry disabled
      shell: bash
    - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      id: app-token
      with:
        client-id: ${{ case(inputs.client-id != '', inputs.client-id, inputs.app-id) }}
        private-key: ${{ inputs.private-key }}
        owner: ${{ github.repository_owner }}
    - run: echo "${{ steps.app-token.outputs.token }}" | gh auth login --with-token
      shell: bash
    - run: gh auth setup-git --hostname github.com
      shell: bash
