name: "GitHub App authentication"
description: ""
inputs:
  app-id:
    description: GitHub App id
    required: true
  private-key:
    description: GitHub App Private Key
runs:
  using: "composite"
  steps:
    - run: gh config set telemetry disabled
      shell: bash
    - uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
      id: app-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: ${{ github.repository_owner }}
    - run: echo "${{ steps.app-token.outputs.token }}" | gh auth login --with-token
      shell: bash
    - run: gh auth setup-git --hostname github.com
      shell: bash
